KitX Dashboard/Data/Config.cs
KitX Dashboard/ViewModels/Pages/Controls/Settings_AboutViewModel.cs
KitX Dashboard/ViewModels/Pages/Controls/Settings_PerformenceViewModel.cs
KitX Dashboard/ViewModels/Pages/SettingsViewModel.cs
KitX Dashboard/Views/MainWindow.axaml.cs
KitX Dashboard/Views/Pages/Controls/Settings_Performence.axaml
KitX Dashboard/Views/Pages/Controls/Settings_Performence.axaml.cs
KitX Dashboard/Views/Pages/SettingsPage.axaml
KitX Dashboard/Views/Pages/SettingsPage.axaml.cs

[Pull Request] 尝试修复进入设置界面的卡顿, 尝试失败, 但是进行了美化

---

KitX Dashboard/App.axaml.cs
KitX Dashboard/Data/Config.cs
KitX Dashboard/Languages/en-us.axaml
KitX Dashboard/Languages/ja-jp.axaml
KitX Dashboard/Languages/zh-cn.axaml
KitX Dashboard/Languages/zh-cnt.axaml
KitX Dashboard/Services/AnouncementManager.cs
KitX Dashboard/Services/WebServer.cs
KitX Dashboard/ViewModels/Pages/Controls/Settings_GeneralViewModel.cs
KitX Dashboard/Views/Pages/Controls/Settings_General.axaml
KitX Rules/KitX.Web.Rules/DeviceInfoStruct.cs
KitX Rules/KitX.Web.Rules/PluginStruct.cs

[Pull Request] 启动时显示公告的配置项, 调色板修复

---

KitX Installer/Installer for Windows/KitX Installer for Windows.cpp
KitX Installer/Installer for Windows/KitX Installer for Windows.vcxproj
KitX Installer/Installer for Windows/Resource.h

[Pull Request] 使用像素风绘制安装包界面

---

KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/Drawer.cs
KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/KitX Installer for Windows in .NET Framework.csproj
KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/MainForm.Designer.cs
KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/MainForm.cs
KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/Program.cs
KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/Properties/app.manifest
KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/UninstallForm.Designer.cs
KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/UninstallForm.cs
KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/UninstallForm.resx

[Pull Request] Windows 平台安装包大致竣工

---

KitX Contracts/KitX.Contract.CSharp/KitX.Contract.CSharp.csproj
KitX File Format Helper/KitX.KXP.Helper/KitX.KXP.Helper.csproj
KitX Rules/KitX.Web.Rules/KitX.Web.Rules.csproj

[Pull Request] 📝 Chore: 新的版本号规则

---

KitX Rules/KitX.Web.Rules/KitX.Web.Rules.csproj

[Pull Request] 📝 Chore: 艹, 这个忘改了

---

.github/workflows/build-push-packages.yml
.github/workflows/build.yml

[Pull Request] 📝 Chore: 推送包转为手动执行

---

.github/workflows/build-publish-packages.yml

[Pull Request] 📝 Chore: 呃, 修复!

---

KitX.sln

[Pull Request] 📝 Chore: 解决方案 引用更新

---

.github/workflows/build-publish-packages.yml

[Pull Request] 📝 Chore: 艹

---

KitX Dashboard/KitX Dashboard.csproj
KitX Loaders/KitX.Loader.WPF.Core/KitX.Loader.WPF.Core.csproj
KitX Loaders/KitX.Loader.Winform.Core/KitX.Loader.Winform.Core.csproj
KitX Official Plugins/TestPlugin.WPF.Core/TestPlugin.WPF.Core.csproj
KitX Test/KitX File Format Helper/KitX.KXP.Helper.Test/KitX.KXP.Helper.Test.csproj

[Pull Request] 📝 Chore: NuGet 更新

---

KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/MainForm.cs

[Pull Request] Win安装包有关权限的改进

---

KitX Installer/Installer for Windows/KitX Installer for Windows in .NET Framework/MainForm.cs

[Pull Request] 💾 🔧 Feat, Fix(Installer): 改用文件信息的产品版本,而不是从程序集中获取

---

README.md

[Pull Request] 📄 Docs: 并不能支持 win7, win8 [skip ci]

---

KitX Dashboard/KitX Dashboard.csproj
KitX Loaders/KitX.Loader.WPF.Core/KitX.Loader.WPF.Core.csproj
KitX Loaders/KitX.Loader.WPF.Framework/KitX.Loader.WPF.Framework.csproj
KitX Loaders/KitX.Loader.WPF.Framework/packages.config
KitX Loaders/KitX.Loader.Winform.Core/KitX.Loader.Winform.Core.csproj
KitX Loaders/KitX.Loader.Winform.Framework/KitX.Loader.Winform.Framework.csproj
KitX Loaders/KitX.Loader.Winform.Framework/packages.config
KitX Official Plugins/TestPlugin.WPF.Core/TestPlugin.WPF.Core.csproj
KitX Test/KitX File Format Helper/KitX.KXP.Helper.Test/KitX.KXP.Helper.Test.csproj

[Pull Request] 📝 Chore: 全面升级新的重定向目标包的项目库

---

.editorconfig
KitX Rules/KitX.Web.Rules/Function.cs
KitX Test/KitX File Format Helper/KitX.KXP.Helper.Test/KXP封装测试.cs
KitX.sln

[Pull Request] 关于Web.Rules.Function

---

ErrorCodes.md

[Pull Request] 📄 Docs: 错误代码 | Error Codes

---

KitX Dashboard/KitX Dashboard.csproj
KitX Loaders/KitX.Loader.WPF.Core/KitX.Loader.WPF.Core.csproj
KitX Loaders/KitX.Loader.WPF.Framework/KitX.Loader.WPF.Framework.csproj
KitX Loaders/KitX.Loader.WPF.Framework/packages.config
KitX Loaders/KitX.Loader.Winform.Core/KitX.Loader.Winform.Core.csproj
KitX Loaders/KitX.Loader.Winform.Framework/KitX.Loader.Winform.Framework.csproj
KitX Loaders/KitX.Loader.Winform.Framework/packages.config
KitX Official Plugins/TestPlugin.WPF.Core/TestPlugin.WPF.Core.csproj
KitX Official Plugins/TestPlugin.WPF.Winform/TestPlugin.WPF.Winform.csproj
KitX Official Plugins/TestPlugin.WPF.Winform/packages.config
KitX Test/KitX File Format Helper/KitX.KXP.Helper.Test/KitX.KXP.Helper.Test.csproj

[Pull Request] 📝 Chore: 更新 Nuget 包引用

---

KitX Dashboard/KitX Dashboard.csproj

Correct a typo in KitX Dashboard.csproj

---

README.md

[Pull Request] 📄 Docs: 补全支持的平台

---

KitX Dashboard/Data/Config.cs
KitX Dashboard/Program.cs
KitX Official Website/KitX Website/.config/dotnet-tools.json
KitX Official Website/KitX Website/Pages/Download.razor
KitX Official Website/KitX Website/Pages/_Layout.cshtml
KitX Official Website/KitX Website/Properties/PublishProfiles/kitx-official-website-server-linux-x64-single.pubxml
KitX Official Website/KitX Website/Shared/DownloadArea.razor
KitX Official Website/KitX Website/Shared/MainLayout.razor
KitX Official Website/KitX Website/i18ntext/Text.cn.json
KitX Official Website/KitX Website/i18ntext/Text.en.json
KitX Official Website/KitX Website/wwwroot/css/download-area.css
KitX Official Website/KitX Website/wwwroot/js/download-area.js

[Pull Request] 一些更新

---

README.md

[Pull Request] 📄 Docs: 图标更新

---

README.md

[Pull Request] 📄 Docs: 更新支持情况, 添加新的路线图

---

KitX Docs/README/zh-cn/README.md
KitX Docs/README/zh-cn/struct/README.md

[Pull Request] 📄 Docs: 目录与项目架构

---

README.md

[Pull Request] 📄 Docs: 链接修正, 更多折叠

---

KitX Dashboard/Data/Config.cs
KitX Dashboard/Services/WebServer.cs
KitX Loaders/KitX.Loader.WPF.Core/App.xaml.cs

[Pull Request] 🔧 Fix(Dashboard): 超出缓冲了, 怪不得, Close #133.

---

KitX Dashboard/Data/AppConfig.cs
KitX Dashboard/Helper.cs
KitX Dashboard/Languages/en-us.axaml
KitX Dashboard/Languages/ja-jp.axaml
KitX Dashboard/Languages/zh-cn.axaml
KitX Dashboard/Languages/zh-cnt.axaml
KitX Dashboard/Models/EventHandlers.cs
KitX Dashboard/Models/SurpportLogLevel.cs
KitX Dashboard/Services/PluginsManager.cs
KitX Dashboard/ViewModels/Pages/Controls/PluginCardViewModel.cs
KitX Dashboard/ViewModels/Pages/Controls/Settings_PerformenceViewModel.cs
KitX Dashboard/ViewModels/Pages/Controls/Settings_UpdateViewModel.cs
KitX Dashboard/Views/Pages/Controls/Settings_Performence.axaml
KitX Dashboard/Views/Pages/Controls/Settings_Update.axaml
KitX Dashboard/Views/Pages/Controls/Settings_Update.axaml.cs
KitX Dashboard/Views/Pages/SettingsPage.axaml
KitX Dashboard/Views/Pages/SettingsPage.axaml.cs

[Pull Request] 日志系统及设置UI大改

---

KitX Dashboard/Languages/en-us.axaml
KitX Dashboard/Languages/ja-jp.axaml
KitX Dashboard/Languages/zh-cn.axaml
KitX Dashboard/Languages/zh-cnt.axaml
KitX Dashboard/ViewModels/Pages/Controls/Settings_UpdateViewModel.cs
KitX Dashboard/Views/Pages/Controls/Settings_About.axaml
KitX Dashboard/Views/Pages/Controls/Settings_General.axaml
KitX Dashboard/Views/Pages/Controls/Settings_Personalise.axaml
KitX Dashboard/Views/Pages/Controls/Settings_Update.axaml
KitX Loaders/KitX.Loader.WPF.Core/App.xaml.cs

1. 更新检查新增单步锁, 防止同时并发请求
2. 更新页组件将按照路径的目录结构进行排序, 更好看了
3. 更新页更新按钮设为主题色
4. Loader.WPF.Core 取消在收到报文之后立即显示的调试手段
4 -> issue #145.

[Pull Request] 更新页逻辑 UI 优化, 其它优化

---

KitX Dashboard/Languages/en-us.axaml
KitX Dashboard/Languages/ja-jp.axaml
KitX Dashboard/Languages/zh-cn.axaml
KitX Dashboard/Languages/zh-cnt.axaml
KitX Dashboard/Views/Pages/Controls/DeviceCard.axaml

[Pull Request] Device：设备属性

---

KitX Dashboard/KitX Dashboard.csproj
KitX Dashboard/Languages/en-us.axaml
KitX Dashboard/Languages/ja-jp.axaml
KitX Dashboard/Languages/zh-cn.axaml
KitX Dashboard/Languages/zh-cnt.axaml
KitX Dashboard/ViewModels/Pages/Controls/Settings_UpdateViewModel.cs
KitX Dashboard/Views/MainWindow.axaml
KitX Dashboard/Views/Pages/Controls/DeviceCard.axaml
KitX Dashboard/Views/Pages/Controls/Settings_Update.axaml

* 主窗体导航添加提示
* 设备卡片类型 UI , 语言更新
* 更新页 UI 更新
* 更新页无可用更新时禁用更新按钮
none

[Pull Request] 一些 UI 更新

---

.gitmodules

* https://github.com/LYF511/KitX.Loader.Python
* https://github.com/Crequency/KitX-Mobile

[Pull Request] 引用: KitX.Loader.Python KitX-Mobile

---

README.md

[Pull Request] Update README

---

.github/workflows/build-publish-packages.yml

[Pull Request] CI Environment 尝试

---

.github/FUNDING.yml

1. 修改 .github/FUNDING.yml 文件以便正确显示赞助链接

[Pull Request] 关于赞助 [skip ci]

---

commit.template.txt

[Pull Request] Updated commit template

---

.github/CONTRIBUTING.md
.github/SECURITY.md

Typo:
- [CONTRIBUTING.md](https://github.com/Crequency/KitX/blob/main/.github/CONTRIBUTING.md) Turn `commt` -> `commit`
Modify:
- [SECURITY](https://github.com/Crequency/KitX/blob/main/.github/SECURITY.md) Updated.

[Pull Request] Motification related to documents.

---

ToolKits/KitX.ToolKits.Publisher/Program.cs
ToolKits/start.ps1
ToolKits/start.sh

In docs, we know that we need to use `start.sh dashboard` or other set in different of `dashboard` to init repo.
I added `list` command so that we can know which set we can select to init repo.
Use like `./ToolKits/start.sh list`
<br>

[Pull Request] Add `list` command for start script

---

.github/workflows/issue-commented.yml

Fixes:
- Use `created` condition to filter comments.
- Use environment variables from github to pass issue number to labeler.
<br>

[Pull Request] Fix condition error, and labeler error in `issue-commented.yml`

---

ToolKits/Actions/pr_auto_rename.py

[Pull Request] Test fixing for new action workflow file that auto rename pr

---

ToolKits/Actions/check_new_commit.py

Features:
- New python script checks that if the latest commit was out of specific time duration.
<br>

[Pull Request] New script for github action that check latest commit date

---

.github/workflows/publish-packages.yml

[Pull Request] Allow pass command when manually invoke `Actions.PublishPackages`
